language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
  licenses:
    - 'android-sdk-license-.+'

before_script:
  - echo y | android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | android update sdk --no-ui --all --filter extra-android-support
  - echo y | android update sdk --no-ui --all --filter build-tools-28.0.3

script:
  - ./gradlew build lint test && ./gradlew assembleDebug

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file: "app/build/outputs/apk/debug/app-debug.apk"
